model_path: "configurations/FeedForwardGeneration/"

sample_size: 100000
augmented_data: "augmented.csv"

tokenizer:
  type: "bpe"
  # checkpoint: "configurations/FeedForwardGeneration/tokenizer.json"
  params:
    vocab_size: 5000
    min_frequency: 2
    
model:
  type: "feedforward-generation"
  params:
    # must match vectorizer.max_features
    input_dim: 1000
    hidden_dims: [256, 256]
    vocab_size: 5000
    dropout_rate: 0.3
    lr: 0.005
    epochs: 20
    batch_size: 64
    max_length: 256
    device: "cuda"