model_path: examples/NaiveBayes/
dataset_name: "jniimi/tripadvisor-review-rating"
review_col: "review"
label_col: "overall"
sample_size: 50000
balance: true
balance_percentage: 0.8
augmentation_methods:
  - "synonym"
  - "sentence_shuffle"
  - "word_deletion"

# Vectorizer Configuration
vectorizer:
  type: tf-idf
  params:
    max_features: 1000 # Maximum number of features 
    min_df: 5
    stop_words: english

# Model Configuration
model:
  type: naive-bayes
  params:
    alpha: 1.0
    fit_prior: true
