# Configuration for TripAdvisor Review Generator

# Path to save model artifacts
model_path: "configurations/Rnn_Generative/"

# Dataset information
dataset_name: "jniimi/tripadvisor-review-rating"
review_col: "review"
label_col: "overall"
sample_size: 1000
# balance: true
# balance_percentage: 0.8
# augmentation_methods:
#   - "synonym"
#   - "sentence_shuffle"
#   - "word_deletion"

# Tokenizer configuration
tokenizer:
  type: "bpe"
  params:
    vocab_size: 5000
    min_frequency: 2

# Model configuration
model:
  type: "rnn_generator"
  # checkpoint: "configurations/Rnn_Generative/best_model.pt"

  params:
    vocab_size: 5000
    embedding_dim: 256
    hidden_dim: 512
    num_layers: 2
    dropout: 0.3
    lr: 0.001
    epochs: 20
    batch_size: 64
    max_length: 256
    device: "cpu"  # or "cpu" if no GPU is available
